apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: example
  source:
    repoURL: git@github.com:UUVtQD/sergio-argocd-example-apps.git
    targetRevision: HEAD
    path: apps/example-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
